# Generated by Django 4.2.7 on 2023-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
