# Generated by Django 4.2.7 on 2023-11-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapi', '0002_sport_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sport Description'),
        ),
    ]
