# Generated by Django 4.2.7 on 2023-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapi', '0003_alter_sport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='sportsapi.category', verbose_name='Sport Categories'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='skill_levels',
            field=models.ManyToManyField(blank=True, null=True, to='sportsapi.skilllevel', verbose_name='Skill Levels'),
        ),
    ]
