# Generated by Django 4.2.7 on 2023-11-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_city_facility_country_and_more'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='facility.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_administrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
