# Generated by Django 4.2.7 on 2023-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_customuser_city_customuser_coutry_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
