# Generated by Django 4.2.7 on 2023-11-06 16:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapi', '0001_initial'),
        ('facility', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='facility',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='facility',
            name='gender_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Men', 'Men Only'), ('Women', 'Women Only'), ('Mixed', 'Mixed Use')], default=['Mixed'], max_length=12, verbose_name='GENDER CHOICES'),
        ),
        migrations.AddField(
            model_name='facility',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AddField(
            model_name='facility',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='sportsapi.sport', verbose_name='Available Sports'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facility Address'),
        ),
    ]
