# Generated by Django 4.2.7 on 2023-11-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_city_facility_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='address',
            new_name='location_address',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='facility',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Image URL'),
        ),
        migrations.AddField(
            model_name='facility',
            name='state',
            field=models.CharField(blank=True, default='Ankara', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(blank=True, default='Turkey', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
